// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAow0lgTbmwZHUCkiNQvdmhVcZk0rVfKdQ',
    appId: '1:65815273928:web:0664c1bc72debd4afe20fd',
    messagingSenderId: '65815273928',
    projectId: 'taskman-55dd2',
    authDomain: 'taskman-55dd2.firebaseapp.com',
    storageBucket: 'taskman-55dd2.firebasestorage.app',
    measurementId: 'G-0MR35CYQQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoW_XJw_GbEi9znnXRtmFR5mAPgiIQ_Wg',
    appId: '1:65815273928:android:ef74625106577e63fe20fd',
    messagingSenderId: '65815273928',
    projectId: 'taskman-55dd2',
    storageBucket: 'taskman-55dd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALje7z0wM2CYBi3mMf79OPKH03akKT3bA',
    appId: '1:65815273928:ios:d3b7bd2bc668d1fffe20fd',
    messagingSenderId: '65815273928',
    projectId: 'taskman-55dd2',
    storageBucket: 'taskman-55dd2.firebasestorage.app',
    iosBundleId: 'com.example.taskMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALje7z0wM2CYBi3mMf79OPKH03akKT3bA',
    appId: '1:65815273928:ios:d3b7bd2bc668d1fffe20fd',
    messagingSenderId: '65815273928',
    projectId: 'taskman-55dd2',
    storageBucket: 'taskman-55dd2.firebasestorage.app',
    iosBundleId: 'com.example.taskMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAow0lgTbmwZHUCkiNQvdmhVcZk0rVfKdQ',
    appId: '1:65815273928:web:68450d2d6e89e54bfe20fd',
    messagingSenderId: '65815273928',
    projectId: 'taskman-55dd2',
    authDomain: 'taskman-55dd2.firebaseapp.com',
    storageBucket: 'taskman-55dd2.firebasestorage.app',
    measurementId: 'G-1892T79E62',
  );
}
